### PR TITLE
add about content to homepage

### PR DESCRIPTION
**Pull request by readmey**
#2 

display about content on homepage

### CODE REVIEW

**Comment by readmey** [comment]
@joshghent could you give me feedback about this PR :)

**Comment by readmey** [comment]
@joshghent I didnt received any feedback and just wanted to check again. Kind regards

**Comment by joshghent** [comment]
Hi @readmey sorry I wasn't very clear with the spec on this and for not reviewing sooner! Thank you for your assistance with this! 🎉 

So if possible, could the about content be included in the main panel with the two buttons please?
Additionally, could the about content come into view when clicking a down arrow button like this: https://fontawesome.com/v4.7.0/icon/arrow-down

Could you please make sure that the width of the content is capped at around 70% of the visible viewport please 👍 

Thank you in advance! Appreciate your hard work on this :) I will be sure to mark with hacktoberfest

**Comment by readmey** [comment]
@joshghent i made several changes, i moved the form into an own component, just added the about content to the main panel and add the icon you mentioned inside.

**Comment by joshghent** [comment]
@readmey This is awesome! 🎉 Thank you so much for your hard work on this! It's really lovely of you to do some work for a charity. Thank you! Hope you continue to contribute to OSS. Let me know if you need any help :)

**Pull request merged**
